# Generated by Django 5.2.8 on 2025-11-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('nko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cities',
            field=models.ManyToManyField(blank=True, to='nko.city', verbose_name='Города'),
        ),
    ]
