# Generated by Django 5.2.8 on 2025-11-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('nko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nko.nko', verbose_name='НКО'),
        ),
    ]
