# Generated by Django 5.2.8 on 2025-11-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='NKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название НКО')),
                ('description', models.TextField(verbose_name='Описание деятельности')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='nko_logos/', verbose_name='Логотип')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='ВКонтакте')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('has_access', models.BooleanField(default=False, verbose_name='Есть доступ к публикациям')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='nko.category', verbose_name='Категории')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nko.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'НКО',
                'verbose_name_plural': 'НКО',
            },
        ),
    ]
