# Generated by Django 5.2.8 on 2025-11-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nko', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nko',
            name='categories',
        ),
        migrations.AddField(
            model_name='nko',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nko.category', verbose_name='Категория'),
        ),
    ]
