# Generated by Django 5.2.8 on 2025-11-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='description',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='hashtags',
            field=models.ManyToManyField(related_name='knowledge_bases', to='knowledge_base.hashtag'),
        ),
    ]
